import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {ReactQueryProvider} from "@/app/ReactQueryProvider";
import Navbar from "@/components/Navbar";
import {ThemeProvider} from '@mui/material/styles';
import {theme} from '@/utils/theme';
import CssBaseline from '@mui/material/CssBaseline';


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ReactQueryProvider>
            <ThemeProvider theme={theme}>
                <CssBaseline/>
                <html lang="fa" dir="rtl">
                <body className={inter.className}>
                <Navbar/>
                {children}
                </body>
                </html>
            </ThemeProvider>
        </ReactQueryProvider>
    )
}
