import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {ReactQueryProvider} from "@/app/ReactQueryProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ReactQueryProvider>
            <html lang="fa" dir="rtl">
            <body className={inter.className}>{children}</body>
            </html>
        </ReactQueryProvider>
    )
}
